# Generated by Django 3.0.7 on 2020-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200625_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_password', models.CharField(max_length=4, verbose_name='OTP-пароль')),
            ],
            options={
                'verbose_name': 'OTP-пароль',
                'verbose_name_plural': 'OTP-пароли',
            },
        ),
    ]
