# Generated by Django 3.0.7 on 2020-06-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otpverification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpVerification',
        ),
    ]
