# Generated by Django 3.0.7 on 2020-06-28 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAuthentificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_password', models.CharField(max_length=4, verbose_name='OTP-пароль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP-пароль',
                'verbose_name_plural': 'OTP-пароли',
            },
        ),
    ]
